In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("essays.csv",sep=",", encoding='cp1252')
df.head()

#AUTHID                                               TEXT cEXT  \
0  1997_504851.txt  Well, right now I just woke up from a mid-day ...    n   
1  1997_605191.txt  Well, here we go with the stream of consciousn...    n   
2  1997_687252.txt  An open keyboard and buttons to push. The thin...    n   
3  1997_568848.txt  I can't believe it!  It's really happening!  M...    y   
4  1997_688160.txt  Well, here I go with the good old stream of co...    y   

  cNEU cAGR cCON cOPN  
0    y    y    n    y  
1    n    y    n    n  
2    y    n    y    y  
3    n    y    y    n  
4    n    y    n    y

In [21]:
df['cEXT'] = df['cEXT'].map(
                   {'y':1 ,'n':0})

df.head()

#AUTHID                                               TEXT  cEXT  \
0  1997_504851.txt  Well, right now I just woke up from a mid-day ...     0   
1  1997_605191.txt  Well, here we go with the stream of consciousn...     0   
2  1997_687252.txt  An open keyboard and buttons to push. The thin...     0   
3  1997_568848.txt  I can't believe it!  It's really happening!  M...     1   
4  1997_688160.txt  Well, here I go with the good old stream of co...     1   

  cNEU cAGR cCON cOPN  
0    y    y    n    y  
1    n    y    n    n  
2    y    n    y    y  
3    n    y    y    n  
4    n    y    n    y

In [22]:

#Labels are converted from y and n to 1 and 0
df['cNEU'] = df['cNEU'].map(
                   {'y':1 ,'n':0})
df['cAGR'] = df['cAGR'].map(
                   {'y':1 ,'n':0})
df['cCON'] = df['cCON'].map(
                   {'y':1 ,'n':0})
df['cOPN'] = df['cOPN'].map(
                   {'y':1 ,'n':0})

df.head()

#AUTHID                                               TEXT  cEXT  \
0  1997_504851.txt  Well, right now I just woke up from a mid-day ...     0   
1  1997_605191.txt  Well, here we go with the stream of consciousn...     0   
2  1997_687252.txt  An open keyboard and buttons to push. The thin...     0   
3  1997_568848.txt  I can't believe it!  It's really happening!  M...     1   
4  1997_688160.txt  Well, here I go with the good old stream of co...     1   

   cNEU  cAGR  cCON  cOPN  
0     1     1     0     1  
1     0     1     0     0  
2     1     0     1     1  
3     0     1     1     0  
4     0     1     0     1

Tokenization and Vectorization

In [6]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cEXT']
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english', lowercase=True)
wc = tfidf.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(wc, y, train_size = 0.8)
X_train
print(X_train.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cNEU']
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english', lowercase=True)
wc = tfidf.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(wc, y, train_size = 0.8)
X_train
print(X_train.toarray())

[[0.05418695 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.10682868 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [23]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cAGR']
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english', lowercase=True)
wc = tfidf.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(wc, y, train_size = 0.8)
X_train
print(X_train.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cCON']
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english', lowercase=True)
wc = tfidf.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(wc, y, train_size = 0.8)
X_train
print(X_train.toarray())

In [28]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cOPN']
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english', lowercase=True)
wc = tfidf.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(wc, y, train_size = 0.8)
X_train
print(X_train.toarray())

[[0.         0.09676961 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [ ]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cEXT']
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english', lowercase=True)
word_count = cv.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(word_count, y, train_size = 0.8)
X_train

In [ ]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cNEU']
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english', lowercase=True)
word_count = cv.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(word_count, y, train_size = 0.8)
X_train

In [ ]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cAGR']
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english', lowercase=True)
word_count = cv.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(word_count, y, train_size = 0.8)
X_train

In [ ]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cCON']
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english', lowercase=True)
word_count = cv.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(word_count, y, train_size = 0.8)
X_train

In [ ]:
from sklearn.model_selection import train_test_split
#binary classification
x = df['TEXT']
y = df['cOPN']
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english', lowercase=True)
word_count = cv.fit_transform(x.apply(lambda x: np.str_(x))) # Fit the model
X_train, X_test, y_train, y_test = train_test_split(word_count, y, train_size = 0.8)
X_train

Implementation of Models

In [29]:
from sklearn.naive_bayes import MultinomialNB
import matplotlib.pyplot as plt
clf = MultinomialNB(alpha=0.01)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
from sklearn import metrics
acc_score = metrics.accuracy_score(y_test, pred)
precision = metrics.precision_score(y_test, pred)
recall = metrics.recall_score(y_test, pred)
f1_score = metrics.f1_score(y_test, pred, average='macro')
print(acc_score)
print(precision)
print(recall)
print(f1_score)

0.5688259109311741
0.6099585062240664
0.5526315789473685
0.5685271069886455


In [30]:
from sklearn import svm
svm1 = svm.SVC(kernel='linear')
svm1 = svm1.fit(X_train,y_train)
predsvm = svm1.predict(X_test)
acc_score = metrics.accuracy_score(y_test, predsvm)
precision = metrics.precision_score(y_test,predsvm)
recall = metrics.recall_score(y_test,predsvm)
f1_score = metrics.f1_score(y_test, predsvm, average='macro')

print(acc_score)
print(precision)
print(recall)
print(f1_score)


0.6072874493927125
0.6363636363636364
0.631578947368421
0.6051907390623712


In [31]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()
logisticRegr = logisticRegr.fit(X_train, y_train)
lrpred = logisticRegr.predict(X_test)
acc_score = metrics.accuracy_score(y_test, lrpred)
precision = metrics.precision_score(y_test,lrpred)
recall = metrics.recall_score(y_test,lrpred)
f1_score = metrics.f1_score(y_test, lrpred, average='macro')
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != lrpred).sum()))
print(acc_score)
print(precision)
print(recall)
print(f1_score)


Number of mislabeled points out of a total 494 points : 196
0.6032388663967612
0.631578947368421
0.631578947368421
0.6008771929824561


In [32]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100)
rf = rf.fit(X_train, y_train)
rfpred = rf.predict(X_test)
acc_score = metrics.accuracy_score(y_test, rfpred)
precision = metrics.precision_score(y_test,rfpred)
recall = metrics.recall_score(y_test,rfpred)
f1_score = metrics.f1_score(y_test, rfpred, average='macro')
print(acc_score)
print(precision)
print(recall)
print(f1_score)

0.6255060728744939
0.6723404255319149
0.5939849624060151
0.6254308631197564


In [33]:
from sklearn.linear_model import Perceptron
p = Perceptron(random_state=42,max_iter=1000,tol=0.01)
p = p.fit(X_train,y_train)
ppred = p.predict(X_test)
acc_score = metrics.accuracy_score(y_test, ppred)
precision = metrics.precision_score(y_test,ppred)
recall = metrics.recall_score(y_test,ppred)
f1_score = metrics.f1_score(y_test, ppred, average='macro')
#print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != ppred).sum()))
print(acc_score)
print(precision)
print(recall)
print(f1_score)


Number of mislabeled points out of a total 494 points : 216
0.562753036437247
0.5899280575539568
0.6165413533834586
0.558227344992051
